# Updated: 2024-01-02
TAG_MAPPING = {
   "andrew": "andrew",
   "Akane": "Akane",
   "4g9_beat": "Beat", 
   "beat": "Beat",
   "blake": "blake",
   "celmech": "celmech",
   "gris": "gris",
   "hyde": "hyde",
   "hydo": "Hyde",
   "4g9_cooper": "JohnCooper",
   "cooper": "JohnCooper",
   "moonstone": "moonstone",
   "muro": "muro",
   "muro_mech": "muro_mech",
   "oscar": "oscar",
   "P_5.D": "P-5",
   "ravi": "ravi",
   "rv": "rv",
   "slasher": "slasher",
   "yugo": "UGo",
   "sol,": "Soll",
   "soll": "Soll",
   "verdoman": "Verdorman",
   "engel": "engel",
   "4g9_honey": "Hani",
   "sniper_girl": "Hani",
   "joa": "Joa",
   "4g9_joa": "Joa",
   "lora,": "Lora",
   "4g9_lora": "Lora",
   "mother": "Mother",
   "4g9_mother": "Mother",
   "pre": "Pre",
   "4g9_pre": "Pre",
   "4g9_scarlet": "Scarlett",
   "4g9_zp": "ZP",
   "agro": "agro",
   "aguro": "agro",
   "baeksa": "baeksa",
   "beaksa": "Baeksa",
   "blanc": "blanc",
   "chati": "chati",
   "experiment01": "experiment01",
   "experiment02": "experiment02",
   "employee": "employee",
   "hayden": "hayden",
   "hikey_female": "Hayden",
   "heize": "heize",
   "singer": "Heize",
   "singer_female": "Heize",
   "singer_male": "Oscar",
   "hikey": "Hyki",
   "hyki": "hyki",
   "irie": "Irey",
   "lettergirl": "lettergirl",
   "mari": "mari",
   "milter": "milter",
   "milter_female": "Milter",
   "navy_girl": "navy_girl",
   "nino": "nino",
   "noah": "noah",
   "persa": "persa",
   "fersa": "Persa",
   "father": "father",
   "rem": "rem",
   "rinmei": "LinMei",
   "rinshao": "LinXiao",
   "rinshao_female": "LinXiao",
   "ru-i": "RU-i",
   "santos": "santos",
   "santos_female": "Santos",
   "shimizu": "shimizu",
   "space_girl": "Danbi",
   "space girl": "Danbi",
   "armor": "armor",
   "blouse": "blouse",
   "buruma": "buruma",
   "shirt": "shirt",
   "t-shirt": "t-shirt",
   "cardigan": "cardigan",
   "camisole": "camisole",
   "cape": "cape",
   "cassock": "cassock",
   "coat": "coat",
   "fur coat": "fur_coat",
   "fur_coat": "fur_coat",
   "raincoat": "raincoat",
   "jacket": "jacket",
   "blazer": "blazer",
   "business suit": "business_suit",
   "business_suit": "business_suit",
   "chinese clothes": "chinese_clothes",
   "chinese_clothes": "chinese_clothes",
   "male swimwear": "male_swimwear",
   "male_swimwear": "male_swimwear",
   "band uniform": "band_uniform",
   "band_uniform": "band_uniform",
   "school uniform": "school_uniform",
   "school_uniform": "school_uniform",
   "sportswear": "sportswear",
   "tank top": "tank_top",
   "tank_top": "tank_top",
   "gym uniform": "gym_uniform",
   "gym_uniform": "gym_uniform",
   "sweater": "sweater",
   "crop top": "crop_top",
   "crop_top": "crop_top",
   "tuxedo": "tuxedo",
   "winter clothes": "winter_clothes",
   "winter_clothes": "winter_clothes",
   "military uniform": "military_uniform",
   "military_uniform": "military_uniform",
   "apron": "apron",
   "maid": "maid",
   "cheerleader": "cheerleader",
   "nun": "nun",
   "overalls": "overalls",
   "pajamas": "pajamas",
   "police": "police",
   "skirt": "skirt",
   "long skirt": "long_skirt",
   "long_skirt": "long_skirt",
   "shorts": "shorts",
   "pants": "pants",
   "fashion": "fashion",
   "casual": "casual",
   "dress": "dress",
   "wedding": "wedding",
   "mechanical": "mechanical",
   "bikini": "bikini",
   "swimsuit": "swimsuit",
   "ballet": "ballet",
   "robe": "robe",
   "japanese clothes": "japanese_clothes",
   "japanese_clothes": "japanese_clothes",
   "korean clothes": "korean_clothes",
   "korean_clothes": "korean_clothes",
   "animal costume": "animal_costume",
   "animal_costume": "animal_costume",
   "santa costume": "santa_costume",
   "santa_costume": "santa_costume",
   "bodysuit": "bodysuit",
   "bikesuit": "bikesuit",
   "jumpsuit": "jumpsuit",
   "leotard": "leotard",
   "nightgown": "nightgown",
   "kneehighs": "kneehighs",
   "pantyhose": "pantyhose",
   "thighhighs": "thighhighs",
   "shoes": "shoes",
   "boots": "boots",
   "high heels": "high_heels",
   "high_heels": "high_heels",
   "sandals": "sandals",
   "sneakers": "sneakers",
   "headphones": "headphones",
   "mask": "mask",
   "necktie": "necktie",
   "weapon": "weapon",
   "simple background": "simple_background",
   "simple_background": "simple_background",
   "1girl": "girl",
   "1boy": "boy",
   "2boys": "multiple",
   "2girls": "multiple"
}