# Generated Tag Mapping

TAG_MAPPING = {
    '1boy,': 'boy',
    '1girl,': 'girl',
    '4g9_beat,': 'Beat',
    '4g9_cooper,': 'JohnCooper',
    '4g9_honey,': 'Hani',
    '4g9_joa,': 'Joa',
    '4g9_lora,': 'Lora',
    '4g9_mother,': 'Mother',
    '4g9_pre,': 'Pre',
    '4g9_scarlet,': 'Scarlett',
    '4g9_scarlett,': 'Scarlett',
    '4g9_zp,': 'ZP',
    'Akane,': 'Akane',
    'P_5.D,': 'P-5',
    'ZP': 'ZP',
    'agro,': 'Agro',
    'aguro,': 'Agro',
    'akane,': 'Akane',
    'alley,': 'alley',
    'andrew,': 'Andrew',
    'animal costume,': 'animal_costume',
    'animal_costume,': 'animal_costume',
    'apron,': 'apron',
    'autumn,': 'autumn',
    'baeksa,': 'Baeksa',
    'ballet,': 'ballet',
    'band uniform,': 'band_uniform',
    'band_uniform,': 'band_uniform',
    'beaksa,': 'Baeksa',
    'beat,': 'Beat',
    'bikesuit,': 'bikesuit',
    'bikini,': 'bikini',
    'blacky,': 'Blacky',
    'blake,': 'Blake',
    'blanc,': 'Blanc',
    'blazer,': 'blazer',
    'blouse,': 'blouse',
    'bodysuit,': 'bodysuit',
    'boots,': 'boots',
    'boy,': 'boy',
    'business suit,': 'business_suit',
    'business_suit,': 'business_suit',
    'camisole,': 'camisole',
    'campo,': 'Campo',
    'cape,': 'cape',
    'cardigan,': 'cardigan',
    'cassock,': 'cassock',
    'casual,': 'casual',
    'celmech,': 'Celmech',
    'chati,': 'Chati',
    'cheerleader,': 'cheerleader',
    'chinese clothes,': 'chinese_clothes',
    'chinese_clothes,': 'chinese_clothes',
    'christmas,': 'christmas',
    'city,': 'city',
    'coat,': 'coat',
    'cooper,': 'JohnCooper',
    'crime scene,': 'crime-scene',
    'crime-scene,': 'crime-scene',
    'crop top,': 'crop_top',
    'crop_top,': 'crop_top',
    'cyberpunk,': 'cyberpunk',
    'danbi,': 'Danbi',
    'dress,': 'dress',
    'dwight,': 'Dwight',
    'employee,': 'Employee',
    'engel,': 'Engel',
    'experiment01,': 'Experiment01',
    'experiment02,': 'Experiment02',
    'fashion,': 'fashion',
    'father,': 'Father',
    'fersa,': 'Persa',
    'flower,': 'flower',
    'fur coat,': 'fur_coat',
    'fur_coat,': 'fur_coat',
    'get-promoted,': 'get-promoted',
    'girl,': 'girl',
    'gris,': 'Gris',
    'gym uniform,': 'gym_uniform',
    'gym_uniform,': 'gym_uniform',
    'halloween,': 'halloween',
    'hanbok,': 'hanbok',
    'hayden,': 'Hayden',
    'headphones,': 'headphones',
    'heize,': 'Heize',
    'high heels,': 'high_heels',
    'high_heels,': 'high_heels',
    'hikey,': 'Hyki',
    'hikey_female,': 'Hayden',
    'hyde,': 'Hyde',
    'hydo,': 'Hyde',
    'hyki,': 'Hyki',
    'indoors,': 'indoors',
    'irie,': 'Irey',
    'jacket,': 'jacket',
    'japanese clothes,': 'japanese_clothes',
    'japanese_clothes,': 'japanese_clothes',
    'joa,': 'Joa',
    'johncooper': 'JohnCooper',
    'jumpsuit,': 'jumpsuit',
    'kneehighs,': 'kneehighs',
    'korean clothes,': 'hanbok',
    'korean_clothes,': 'hanbok',
    'leotard,': 'leotard',
    'lettergirl,': 'Lettergirl',
    'linxiao,': 'LinXiao',
    'long skirt,': 'long_skirt',
    'long_skirt,': 'long_skirt',
    'maid,': 'maid',
    'male swimwear,': 'male_swimwear',
    'male_swimwear,': 'male_swimwear',
    'mari,': 'Mari',
    'mask,': 'mask',
    'mechanical,': 'mechanical',
    'military uniform,': 'military_uniform',
    'military,': 'military_uniform',
    'military_uniform,': 'military_uniform',
    'milter,': 'Milter',
    'milter_female,': 'Milter',
    'moonstone,': 'Moonstone',
    'mother,': 'Mother',
    'navy_girl,': 'Navy_girl',
    'necktie,': 'necktie',
    'new year,': 'new-year',
    'new-year,': 'new-year',
    'nightgown,': 'nightgown',
    'nino,': 'Nino',
    'noah,': 'Noah',
    'nsagkid,': 'AGKid',
    'nsaiken,': 'Aiken',
    'nsbanny,': 'Banny',
    'nsbibi,': 'Bibi',
    'nsblacky,': 'Blacky',
    'nsboolkkaebi,': 'BoolKKaebi',
    'nsbrody,': 'Brody',
    'nscampo,': 'Campo',
    'nscappuccino,': 'Cappuccino',
    'nscasey,': 'Casey',
    'nschoipro,': 'ChoiPro',
    'nschrono,': 'Chrono',
    'nsdueoksini,': 'Dueoksini',
    'nsflora,': 'Flora',
    'nsglenda,': 'Glenda',
    'nsgoffrey,': 'Goffrey',
    'nshari,': 'Hari',
    'nshiruma,': 'Hiruma',
    'nshoon,': 'Hoon',
    'nshungrymanekin,': 'HungryManekin',
    'nsjackson,': 'Jackson',
    'nsjaeden,': 'Jaeden',
    'nsjenna,': 'Jenna',
    'nslackey,': 'Lackey',
    'nslinmei,': 'LinMei',
    'nslora,': 'Lora',
    'nsmark,': 'Mark',
    'nsmin,': 'Min',
    'nsminibit,': 'Minibit',
    'nsmisspark,': 'MissPark',
    'nsmisspark2,': 'MissPark2',
    'nsmuro,': 'Muro',
    'nsmystic,': 'Mystic',
    'nsnana,': 'Nana',
    'nsnaviifront,': 'NaviiFront',
    'nsnoira,': 'Noira',
    'nsnyx,': 'Nyx',
    'nsoliver,': 'Oliver',
    'nsoscar,': 'Oscar',
    'nsotto,': 'Otto',
    'nsrabbitking,': 'RabbitKing',
    'nsravi,': 'Ravi',
    'nssajang,': 'Sajang',
    'nssanta,': 'Santa',
    'nsselina,': 'Selina',
    'nsseth,': 'Seth',
    'nsshader,': 'ShadeR',
    'nssiren,': 'Siren',
    'nsslammer,': 'Slammer',
    'nsspitz,': 'Spitz',
    'nst8,': 'T8',
    'nst9,': 'T9',
    'nstakeru,': 'Takeru',
    'nstatamoo,': 'Tatamoo',
    'nstotory,': 'Totory',
    'nsvulkan,': 'Vulkan',
    'nsxiu,': 'Xiu',
    'nsyeonwoo,': 'Yeonwoo',
    'nsyujin,': 'Yujin',
    'nszachary,': 'Zachary',
    'nun,': 'nun',
    'ocean,': 'ocean',
    'ohm,': 'Ohm',
    'outdoors,': 'outdoors',
    'overalls,': 'overalls',
    'pants,': 'pants',
    'pantyhose,': 'pantyhose',
    'park,': 'park',
    'persa,': 'Persa',
    'pre,': 'Pre',
    'raincoat,': 'raincoat',
    'rem,': 'Rem',
    'rinshao,': 'LinXiao',
    'rinshao_female,': 'LinXiao',
    'ru-i,': 'RU-i',
    'rv,': 'Rv',
    'sandals,': 'sandals',
    'santa costume,': 'santa_costume',
    'santa_costume,': 'santa_costume',
    'santos,': 'Santos',
    'santos_female,': 'Santos',
    'school uniform,': 'school_uniform',
    'school_uniform,': 'school_uniform',
    'shimizu,': 'Shimizu',
    'shirt,': 'shirt',
    'shoes,': 'shoes',
    'shorts,': 'shorts',
    'simple background,': 'simple_background',
    'simple_background,': 'simple_background',
    'singer,': 'Heize',
    'singer_female,': 'Heize',
    'skirt,': 'skirt',
    'slasher,': 'Slasher',
    'sneakers,': 'sneakers',
    'sniper_girl,': 'Hani',
    'sol,': 'Soll',
    'soll,': 'Soll',
    'space girl,': 'Danbi',
    'space_girl,': 'Danbi',
    'spitz,': 'Spitz',
    'sportswear,': 'sportswear',
    'street,': 'street',
    'sweater,': 'sweater',
    'swimming,': 'swimming',
    'swimsuit,': 'swimsuit',
    't-shirt,': 't-shirt',
    'tank top,': 'tank_top',
    'tank_top,': 'tank_top',
    'thanksgiving-day,': 'thanksgiving-day',
    'thighhighs,': 'thighhighs',
    'train,': 'train',
    'tuxedo,': 'tuxedo',
    'valentine,': 'valentine',
    'verdoman,': 'Verdorman',
    'verdorman.': 'Verdorman',
    'volunteer work,': 'volunteer-work',
    'volunteer-work,': 'volunteer-work',
    'vulkan,': 'Vulkan',
    'weapon,': 'weapon',
    'wedding,': 'wedding',
    'winter clothes,': 'winter-clothes',
    'winter-clothes,': 'winter-clothes',
    'winter-festival,': 'winter-festival',
    'winter_clothes,': 'winter_clothes',
    'yugo,': 'UGo',
    'zp,': 'ZP',
}
