# Generated Tag Mapping

TAG_MAPPING = {
    '1boy,': 'boy',
    '1girl,': 'girl',
    '4g9_beat,': 'Beat',
    '4g9_cooper,': 'JohnCooper',
    '4g9_honey,': 'Hani',
    '4g9_joa,': 'Joa',
    '4g9_lora,': 'Lora',
    '4g9_mother,': 'Mother',
    '4g9_pre,': 'Pre',
    '4g9_scarlet,': 'Scarlett',
    '4g9_scarlett,': 'Scarlett',
    '4g9_zp,': 'ZP',
    'AGKid \\(4G9\\)': 'AGKid',
    'Agro \\(4G9\\)': 'Agro',
    'Aiken \\(4G9\\)': 'Aiken',
    'Akane \\(4G9\\)': 'Akane',
    'Akane,': 'Akane',
    'Andrew \\(4G9\\)': 'Andrew',
    'Baeksa \\(4G9\\)': 'Baeksa',
    'Banny \\(4G9\\)': 'Banny',
    'Beat \\(4G9\\)': 'Beat',
    'Bibi \\(4G9\\)': 'Bibi',
    'Blacky \\(4G9\\)': 'Blacky',
    'Blake \\(4G9\\)': 'Blake',
    'Blanc \\(4G9\\)': 'Blanc',
    'BoolKKaebi \\(4G9\\)': 'BoolKKaebi',
    'Brody \\(4G9\\)': 'Brody',
    'Campo \\(4G9\\)': 'Campo',
    'Cappuccino \\(4G9\\)': 'Cappuccino',
    'Casey \\(4G9\\)': 'Casey',
    'Celmech \\(4G9\\)': 'Celmech',
    'Chati \\(4G9\\)': 'Chati',
    'ChoiPro \\(4G9\\)': 'ChoiPro',
    'Chrono \\(4G9\\)': 'Chrono',
    'Danbi \\(4G9\\)': 'Danbi',
    'Dane \\(4G9\\)': 'Dane',
    'Dueoksini \\(4G9\\)': 'Dueoksini',
    'Dwight \\(4G9\\)': 'Dwight',
    'Employee \\(4G9\\)': 'Employee',
    'Engel \\(4G9\\)': 'Engel',
    'Experiment02 \\(4G9\\)': 'Experiment02',
    'Father \\(4G9\\)': 'Father',
    'Flora \\(4G9\\)': 'Flora',
    'Glenda \\(4G9\\)': 'Glenda',
    'Goffrey \\(4G9\\)': 'Goffrey',
    'Greta \\(4G9\\)': 'Greta',
    'Gris \\(4G9\\)': 'Gris',
    'Hani \\(4G9\\)': 'Hani',
    'Hari \\(4G9\\)': 'Hari',
    'Hayden \\(4G9\\)': 'Hayden',
    'Heize \\(4G9\\)': 'Heize',
    'Hiruma \\(4G9\\)': 'Hiruma',
    'Hoon \\(4G9\\)': 'Hoon',
    'HungryManekin \\(4G9\\)': 'HungryManekin',
    'Hyde \\(4G9\\)': 'Hyde',
    'Hyki \\(4G9\\)': 'Hyki',
    'Irey \\(4G9\\)': 'Irey',
    'Jackson \\(4G9\\)': 'Jackson',
    'Jaeden \\(4G9\\)': 'Jaeden',
    'Jenna \\(4G9\\)': 'Jenna',
    'Joa \\(4G9\\)': 'Joa',
    'JohnCooper \\(4G9\\)': 'JohnCooper',
    'Lackey \\(4G9\\)': 'Lackey',
    'Lettergirl \\(4G9\\)': 'Lettergirl',
    'LinMei \\(4G9\\)': 'LinMei',
    'LinXiao \\(4G9\\)': 'LinXiao',
    'Lora \\(4G9\\)': 'Lora',
    'Mari \\(4G9\\)': 'Mari',
    'Mark \\(4G9\\)': 'Mark',
    'Milter \\(4G9\\)': 'Milter',
    'Min \\(4G9\\)': 'Min',
    'Minibit \\(4G9\\)': 'Minibit',
    'MissPark \\(4G9\\)': 'MissPark',
    'Moonstone \\(4G9\\)': 'Moonstone',
    'Mother \\(4G9\\)': 'Mother',
    'Muro \\(4G9\\)': 'Muro',
    'Mystic \\(4G9\\)': 'Mystic',
    'Nana \\(4G9\\)': 'Nana',
    'NaviiFront \\(4G9\\)': 'NaviiFront',
    'Navy_girl \\(4G9\\)': 'Navy_girl',
    'Nino \\(4G9\\)': 'Nino',
    'Noah \\(4G9\\)': 'Noah',
    'Noira \\(4G9\\)': 'Noira',
    'Nyx \\(4G9\\)': 'Nyx',
    'Ohm \\(4G9\\)': 'Ohm',
    'Oliver \\(4G9\\)': 'Oliver',
    'Oscar \\(4G9\\)': 'Oscar',
    'Otto \\(4G9\\)': 'Otto',
    'P-5 \\(4G9\\)': 'P-5',
    'P_5.D,': 'P-5',
    'Persa \\(4G9\\)': 'Persa',
    'Pre \\(4G9\\)': 'Pre',
    'RU-i \\(4G9\\)': 'RU-i',
    'RabbitKing \\(4G9\\)': 'RabbitKing',
    'Ravi \\(4G9\\)': 'Ravi',
    'Rem \\(4G9\\)': 'Rem',
    'Rv \\(4G9\\)': 'Rv',
    'Sajang \\(4G9\\)': 'Sajang',
    'Santa \\(4G9\\)': 'Santa',
    'Santos \\(4G9\\)': 'Santos',
    'Scarlett \\(4G9\\)': 'Scarlett',
    'Selina \\(4G9\\)': 'Selina',
    'Seth \\(4G9\\)': 'Seth',
    'ShadeR \\(4G9\\)': 'ShadeR',
    'Shimizu \\(4G9\\)': 'Shimizu',
    'Siren \\(4G9\\)': 'Siren',
    'Slammer \\(4G9\\)': 'Slammer',
    'Slasher \\(4G9\\)': 'Slasher',
    'Soll \\(4G9\\)': 'Soll',
    'Spitz \\(4G9\\)': 'Spitz',
    'T8 \\(4G9\\)': 'T8',
    'T9 \\(4G9\\)': 'T9',
    'Takeru \\(4G9\\)': 'Takeru',
    'Tatamoo \\(4G9\\)': 'Tatamoo',
    'Totory \\(4G9\\)': 'Totory',
    'UGo \\(4G9\\)': 'UGo',
    'Verdorman \\(4G9\\)': 'Verdorman',
    'Vulkan \\(4G9\\)': 'Vulkan',
    'Xiu \\(4G9\\)': 'Xiu',
    'Yeonwoo \\(4G9\\)': 'Yeonwoo',
    'Yue \\(4G9\\)': 'Yue',
    'Yujin \\(4G9\\)': 'Yujin',
    'ZP': 'ZP',
    'ZP \\(4G9\\)': 'ZP',
    'Zachary \\(4G9\\)': 'Zachary',
    'agro,': 'Agro',
    'aguro,': 'Agro',
    'akane,': 'Akane',
    'alley,': 'alley',
    'andrew,': 'Andrew',
    'animal costume,': 'animal_costume',
    'animal_costume,': 'animal_costume',
    'apron,': 'apron',
    'autumn,': 'autumn',
    'baeksa,': 'Baeksa',
    'ballet,': 'ballet',
    'bambi,': 'Bambi',
    'band uniform,': 'band_uniform',
    'band_uniform,': 'band_uniform',
    'banjo,': 'Banjo',
    'beaksa,': 'Baeksa',
    'beat,': 'Beat',
    'bikesuit,': 'bikesuit',
    'bikini,': 'bikini',
    'blacky,': 'Blacky',
    'blake,': 'Blake',
    'blanc,': 'Blanc',
    'blazer,': 'blazer',
    'blouse,': 'blouse',
    'bodysuit,': 'bodysuit',
    'boots,': 'boots',
    'boy,': 'boy',
    'bugle,': 'Bugle',
    'business suit,': 'business_suit',
    'business_suit,': 'business_suit',
    'camisole,': 'camisole',
    'campo,': 'Campo',
    'cape,': 'cape',
    'cardigan,': 'cardigan',
    'cassock,': 'cassock',
    'casual,': 'casual',
    'cello,': 'Cello',
    'celmech,': 'Celmech',
    'celmek,': 'Celmech',
    'chati,': 'Chati',
    'cheerleader,': 'cheerleader',
    'chinese clothes,': 'chinese_clothes',
    'chinese_clothes,': 'chinese_clothes',
    'christmas,': 'christmas',
    'city,': 'city',
    'clarinet,': 'Clarinet',
    'coat,': 'coat',
    'cooper,': 'JohnCooper',
    'crime scene,': 'crime-scene',
    'crime-scene,': 'crime-scene',
    'crop top,': 'crop_top',
    'crop_top,': 'crop_top',
    'cyberpunk,': 'cyberpunk',
    'danbi,': 'Danbi',
    'dane,': 'Dane',
    'dress,': 'dress',
    'drumsticks, ': 'Drum',
    'drun, ': 'Drum',
    'dwight,': 'Dwight',
    'employee,': 'Employee',
    'engel,': 'Engel',
    'eunho,': 'Eunho',
    'euphonium,': 'Euphonium',
    'experiment01,': 'Greta',
    'experiment02,': 'Experiment02',
    'fashion,': 'fashion',
    'father,': 'Father',
    'fersa,': 'Persa',
    'flower,': 'flower',
    'flute,': 'Flute',
    'fur coat,': 'fur_coat',
    'fur_coat,': 'fur_coat',
    'get-promoted,': 'get-promoted',
    'girl,': 'girl',
    'gris,': 'Gris',
    'guitar,': 'Guitar',
    'gym uniform,': 'gym_uniform',
    'gym_uniform,': 'gym_uniform',
    'halloween,': 'halloween',
    'hamin,': 'Hamin',
    'hanbok,': 'hanbok',
    'harmonica,': 'Harmonica',
    'harp,': 'Harp',
    'hayden,': 'Hayden',
    'headphones,': 'headphones',
    'heize,': 'Heize',
    'high heels,': 'high_heels',
    'high_heels,': 'high_heels',
    'hikey,': 'Hyki',
    'hikey_female,': 'Hayden',
    'hyde,': 'Hyde',
    'hydo,': 'Hyde',
    'hyki,': 'Hyki',
    'indoors,': 'indoors',
    'irie,': 'Irey',
    'jacket,': 'jacket',
    'japanese clothes,': 'japanese_clothes',
    'japanese_clothes,': 'japanese_clothes',
    'joa,': 'Joa',
    'johncooper': 'JohnCooper',
    'jumpsuit,': 'jumpsuit',
    'keyboard (instrument),': 'Keyboard (instrument)',
    'kneehighs,': 'kneehighs',
    'korean clothes,': 'hanbok',
    'korean_clothes,': 'hanbok',
    'leotard,': 'leotard',
    'lettergirl,': 'Lettergirl',
    'linxiao,': 'LinXiao',
    'long skirt,': 'long_skirt',
    'long_skirt,': 'long_skirt',
    'lyre,': 'Lyre',
    'maid,': 'maid',
    'male swimwear,': 'male_swimwear',
    'male_swimwear,': 'male_swimwear',
    'mari,': 'Mari',
    'mask,': 'mask',
    'mechanical,': 'mechanical',
    'military uniform,': 'military_uniform',
    'military,': 'military_uniform',
    'military_uniform,': 'military_uniform',
    'milter,': 'Milter',
    'milter_female,': 'Milter',
    'moonstone,': 'Moonstone',
    'mother,': 'Mother',
    'navy_girl,': 'Navy_girl',
    'necktie,': 'necktie',
    'new year,': 'new-year',
    'new-year,': 'new-year',
    'nightgown,': 'nightgown',
    'nino,': 'Nino',
    'noa,': 'Noa',
    'noah,': 'Noah',
    'nsagkid,': 'AGKid',
    'nsagro,': 'Agro',
    'nsaiken,': 'Aiken',
    'nsakane,': 'Akane',
    'nsandrew,': 'Andrew',
    'nsbaeksa,': 'Baeksa',
    'nsbanny,': 'Banny',
    'nsbeat,': 'Beat',
    'nsbibi,': 'Bibi',
    'nsblacky,': 'Blacky',
    'nsblake,': 'Blake',
    'nsblanc,': 'Blanc',
    'nsboolkkaebi,': 'BoolKKaebi',
    'nsbrody,': 'Brody',
    'nscampo,': 'Campo',
    'nscappuccino,': 'Cappuccino',
    'nscasey,': 'Casey',
    'nscelmech,': 'Celmech',
    'nscelmek,': 'Celmech',
    'nschati,': 'Chati',
    'nschoipro,': 'ChoiPro',
    'nschrono,': 'Chrono',
    'nsdanbi,': 'Danbi',
    'nsdane,': 'Dane',
    'nsdueoksini,': 'Dueoksini',
    'nsdwight,': 'Dwight',
    'nsemployee,': 'Employee',
    'nsengel,': 'Engel',
    'nsexperiment01,': 'Greta',
    'nsexperiment02,': 'Experiment02',
    'nsfather,': 'Father',
    'nsflora,': 'Flora',
    'nsglenda,': 'Glenda',
    'nsgoffrey,': 'Goffrey',
    'nsgreta,': 'Greta',
    'nsgris,': 'Gris',
    'nshani,': 'Hani',
    'nshari,': 'Hari',
    'nshayden,': 'Hayden',
    'nsheize,': 'Heize',
    'nshiruma,': 'Hiruma',
    'nshoon,': 'Hoon',
    'nshungrymanekin,': 'HungryManekin',
    'nshyde,': 'Hyde',
    'nshyki,': 'Hyki',
    'nsirey,': 'Irey',
    'nsjackson,': 'Jackson',
    'nsjaeden,': 'Jaeden',
    'nsjenna,': 'Jenna',
    'nsjoa,': 'Joa',
    'nsjohncooper,': 'JohnCooper',
    'nslackey,': 'Lackey',
    'nslettergirl,': 'Lettergirl',
    'nslinmei,': 'LinMei',
    'nslinxiao,': 'LinXiao',
    'nslora,': 'Lora',
    'nsmari,': 'Mari',
    'nsmark,': 'Mark',
    'nsmilter,': 'Milter',
    'nsmin,': 'Min',
    'nsminibit,': 'Minibit',
    'nsmisspark,': 'MissPark',
    'nsmisspark2,': 'MissPark',
    'nsmoonstone,': 'Moonstone',
    'nsmother,': 'Mother',
    'nsmuro,': 'Muro',
    'nsmystic,': 'Mystic',
    'nsnana,': 'Nana',
    'nsnaviifront,': 'NaviiFront',
    'nsnavy_girl,': 'Navy_girl',
    'nsnino,': 'Nino',
    'nsnoah,': 'Noah',
    'nsnoira,': 'Noira',
    'nsnyx,': 'Nyx',
    'nsohm,': 'Ohm',
    'nsoliver,': 'Oliver',
    'nsoscar,': 'Oscar',
    'nsotto,': 'Otto',
    'nsp-5,': 'P-5',
    'nspersa,': 'Persa',
    'nspre,': 'Pre',
    'nsrabbitking,': 'RabbitKing',
    'nsravi,': 'Ravi',
    'nsrem,': 'Rem',
    'nsru-i,': 'RU-i',
    'nsrv,': 'Rv',
    'nssajang,': 'Sajang',
    'nssanta,': 'Santa',
    'nssantos,': 'Santos',
    'nsscarlet,': 'Scarlett',
    'nsscarlett,': 'Scarlett',
    'nsselina,': 'Selina',
    'nsseth,': 'Seth',
    'nsshader,': 'ShadeR',
    'nsshimizu,': 'Shimizu',
    'nssiren,': 'Siren',
    'nsslammer,': 'Slammer',
    'nsslasher,': 'Slasher',
    'nssoll,': 'Soll',
    'nsspitz,': 'Spitz',
    'nst-0': 'Experiment02',
    'nst-8,': 'T8',
    'nst-9,': 'T9',
    'nst8,': 'T8',
    'nst9,': 'T9',
    'nstakeru,': 'Takeru',
    'nstatamoo,': 'Tatamoo',
    'nstotory,': 'Totory',
    'nsugo,': 'UGo',
    'nsverdorman,': 'Verdorman',
    'nsvulkan,': 'Vulkan',
    'nsxiu,': 'Xiu',
    'nsyeonwoo,': 'Yeonwoo',
    'nsyue,': 'Yue',
    'nsyujin,': 'Yujin',
    'nszachary,': 'Zachary',
    'nszp,': 'ZP',
    'nun,': 'nun',
    'ocarina,': 'Ocarina',
    'ocean,': 'ocean',
    'ohm,': 'Ohm',
    'organ,': 'Organ',
    'outdoors,': 'outdoors',
    'overalls,': 'overalls',
    'pants,': 'pants',
    'pantyhose,': 'pantyhose',
    'park,': 'park',
    'persa,': 'Persa',
    'piano,': 'Piano',
    'pre,': 'Pre',
    'raincoat,': 'raincoat',
    'recorder,': 'Recorder',
    'rem,': 'Rem',
    'rinshao,': 'LinXiao',
    'rinshao_female,': 'LinXiao',
    'ru-i,': 'RU-i',
    'rv,': 'Rv',
    'sandals,': 'sandals',
    'santa costume,': 'santa_costume',
    'santa_costume,': 'santa_costume',
    'santos,': 'Santos',
    'santos_female,': 'Santos',
    'saxophone,': 'Saxophone',
    'school uniform,': 'school_uniform',
    'school_uniform,': 'school_uniform',
    'shimizu,': 'Shimizu',
    'shirt,': 'shirt',
    'shoes,': 'shoes',
    'shorts,': 'shorts',
    'simple background,': 'simple_background',
    'simple_background,': 'simple_background',
    'singer,': 'Heize',
    'singer_female,': 'Heize',
    'skirt,': 'skirt',
    'slasher,': 'Slasher',
    'sneakers,': 'sneakers',
    'sniper_girl,': 'Hani',
    'sol,': 'Soll',
    'soll,': 'Soll',
    'space girl,': 'Danbi',
    'space_girl,': 'Danbi',
    'spitz,': 'Spitz',
    'sportswear,': 'sportswear',
    'street,': 'street',
    'sweater,': 'sweater',
    'swimming,': 'swimming',
    'swimsuit,': 'swimsuit',
    't-shirt,': 't-shirt',
    'tank top,': 'tank_top',
    'tank_top,': 'tank_top',
    'thanksgiving-day,': 'thanksgiving-day',
    'thighhighs,': 'thighhighs',
    'train,': 'train',
    'trombone,': 'Trombone',
    'trumpet,': 'Trumpet',
    'tuba,': 'Tuba',
    'tuxedo,': 'tuxedo',
    'valentine,': 'valentine',
    'verdoman,': 'Verdorman',
    'verdorman.': 'Verdorman',
    'viola (instrument),': 'Viola (instrument)',
    'violin,': 'Violin',
    'volunteer work,': 'volunteer-work',
    'volunteer-work,': 'volunteer-work',
    'vulkan,': 'Vulkan',
    'weapon,': 'weapon',
    'wedding,': 'wedding',
    'winter clothes,': 'winter-clothes',
    'winter-clothes,': 'winter-clothes',
    'winter-festival,': 'winter-festival',
    'winter_clothes,': 'winter_clothes',
    'yejun,': 'Yejun',
    'yue,': 'Yue',
    'yugo,': 'UGo',
    'zp,': 'ZP',
}
